config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :photos
  root 'events#home'

end

app/models/event.rb
class Event < ActiveRecord::Base
	has_many :photos

	validates :title, presence: true

	scope :completed, ->{ where(completed: false) }
	scope :uncompleted, ->{ where(completed: true) }
	scope :order_desc, ->{ order('datetime DESC') }

	def select_three_random_photos
		array = []
		return [] if photos.empty?
		array << photos.sample
		array << photos.sample
		array << photos.sample
		array
	end

end

app/models/photo.rb
class Photo < ActiveRecord::Base
	belongs_to :event

	validates :photo, presence: true

	mount_uploader :photo, PhotoUploader
	

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

	def home
		@events_not = Event.where(completed: false)
		@events_yes = Event.where(completed: true).order_desc		
	end

	def show
		@event = Event.find(params[:id])
		@photos = Photo.where(event: @event)
	end

	def new
		@event = Event.new
	end

	def create
		@event = Event.new(event_params)
		if @event.save
			redirect_to event_path(@event), notice: "Your event has been added"
		else 
			render 'new'
		end
	end

private 
	def event_params
		params.require(:event).permit(:title, :description, :datetime, :completed)
	end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
	def index 
		@photos = Photo.all
	end

	def new
		@photo = Photo.new
	end

	def create
		@photo = Photo.new(photo_params)
		event = Event.find(photo_params[:event_id])
		if @photo.save
      redirect_to event_path(event), notice: "The photo has been added."
    else
      render "new"
    end
	end

	def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy
    redirect_to root_path, notice:  "The photo has been deleted."
  end

private 
	def photo_params
		params.require(:photo).permit(:photo, :description, :event_id)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper

  def carousel_for(images)
    Carousel.new(self, images).html
  end

  class Carousel
    def initialize(view, images)
      @view, @images = view, images
      @uid = SecureRandom.hex(6)
    end

    def html
      content = safe_join([indicators, slides, controls])
      content_tag(:div, content, id: uid, class: 'carousel slide')
    end

    private

    attr_accessor :view, :images, :uid
    delegate :link_to, :content_tag, :image_tag, :safe_join, to: :view

    def indicators
      items = images.count.times.map { |index| indicator_tag(index) }
      content_tag(:ol, safe_join(items), class: 'carousel-indicators')
    end

    def indicator_tag(index)
      options = {
        class: (index.zero? ? 'active' : ''),
        data: { 
          target: uid, 
          slide_to: index
        }
      }

      content_tag(:li, '', options)
    end

    def slides
      items = images.map.with_index { |image, index| slide_tag(image, index.zero?) }
      content_tag(:div, safe_join(items), class: 'carousel-inner')
    end

    def slide_tag(image, is_active)
      options = {
        class: (is_active ? 'item active' : 'item'),
        
      }
      img = image_tag(image.photo)
      cap = content_tag(:div, content_tag(:h3, image.description), class: "carousel-caption")
      content_tag(:div, safe_join([img, cap]), options)
    end

    def controls
      safe_join([control_tag('left'), control_tag('right')])
    end

    def control_tag(direction)
      options = {
        class: "#{direction} carousel-control",
        data: { slide: direction == 'left' ? 'prev' : 'next' }
      }

      icon = content_tag(:i, '', class: "glyphicon glyphicon-chevron-#{direction}")
      control = link_to(icon, "##{uid}", options)
    end
  end

end

app/helpers/photo_helper.rb
module PhotoHelper
end

app/views/events/_add_photo.html.slim
.container style="dysplay: block; margin-right: 5px"
	= form_for Photo.new, html: { multipart: true } do |f|
		= f.hidden_field :event_id, value: event.id
		p 
			.form-group
			= f.file_field :photo
			= f.hidden_field :photo_cache
			= f.submit "Add", class: "btn btn-success"

app/views/events/home.html.slim
.row
	- @events_not.each do |event|
		.jumbotron
			p
				h2 
					= link_to event.title, event
				h3 = event.description
				h3 = event.datetime.to_s
			- event.select_three_random_photos.each do |photo|
				img.img-thumbnail src="#{photo.photo.medium.url}"
	.col-md-12 
		h1 Прошедшие события
	- @events_yes.each do |event|
		.jumbotron style='background: #e69595'
			p
				h2 
					= link_to event.title, event
				h3 = event.description
				h3 = event.datetime.to_s
			- event.select_three_random_photos.each do |photo|
				img.img-thumbnail src="#{photo.photo.medium.url}"

app/views/events/new.html.slim
.container.highlight
	= form_for @event, html: { multiply: true, class: 'form-horizontal', role: 'form'} do |f| 
		.form_group
			= f.label :title, class: "col-sm-2 control-label"
			.col-sm-10
				= f.text_field :title, class: 'form-control', placeholder: 'I love you'

		.form_group
			= f.label :description, class: "col-sm-2 control-label"
			.col-sm-10 = f.text_area :description, class: 'form-control', placeholder: 'I love you'

		.form_group
			= f.label :Date, class: "col-sm-2 control-label"
			.col-sm-10 = f.date_field :datetime, start_year: 2017, class: 'form-control'

		.form_group
			= f.label :completed, class: "col-sm-2 control-label"
			.col-sm-10 = f.check_box :completed, class: 'form-control'
		
		.form_group 
			= f.submit :submit, class: 'col-sm-2 btn btn-default'

app/views/events/show.html.slim
.container style="background: white; border-radius: 5px; padding-bottom: 50px"
	
 
	h1 = @event.title
	h3 = @event.description

	= render 'add_photo.html.slim', event: @event

	= carousel_for(@photos)

app/views/layouts/_header.html.slim
nav class="navbar navbar-default" role="navigation"
	.container
		.havbar-header
			= link_to "Love Events", root_path, class: "navbar-brand"
		ul.nav *{class: ["navbar-nav", "navbar-right"]}
			li
				a.nav href="#{new_event_path}"
					span.glyphicon.glyphicon-plus
					| Add Event 
					
					
			/ li.dropdown
			/ 	a.dropdown-toggle data-toggle="dropdown" href="#"
			/ 		- if signed_in?
			/ 			| #{current_user.full_name}
			/ 		- else 
			/ 			| Guest
			/ 		span.caret
			/ 	ul.dropdown-menu@menu
			/ 		- if signed_in?
			/ 			li
			/ 				a href=profile_path
			/ 					span.glyphicon.glyphicon-user 
			/ 					span.glyphicon-class   Show Profile
			/ 			li.divider
			/ 			li 
			/ 				a href=sign_out_path data-method="delete"
			/ 					span.glyphicon.glyphicon-off
			/ 					span.glyphicon-class   Logout
			/ 		- else 
			/ 			li = link_to "Login", sign_in_path

app/views/layouts/application.html.slim
doctype html
html
	head
		title Love Events
		= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
		= javascript_include_tag 'application', 'data-turbolinks-track' => true
		= csrf_meta_tags

	body.app
		= render "layouts/header"

		.container
			= yield 
			

app/views/photos/index.html.slim
- if !flash[:notice].blank? 
  .alert.alert-info
    = flash[:notice] 
br
  = link_to "New Photo", new_photo_path, class: "btn btn-primary" 
br
br
table.table.table-bordered.table-striped
  thead
    tr
      th Description
      th Download Link
      th &nbsp;
    
  tbody
    - @photos.each do |photo| 
      tr
        td = photo.description 
        td = image_tag(photo.photo)
        

app/views/photos/new.html.slim
.well
  = form_for @photo, html: { multipart: true } do |f| 
    = f.label :description
    = f.text_field :description
    = f.label :photo 
    = f.file_field :photo 
    = f.submit "Save", class: "btn btn-primary" 
  